# Site
repository: ineverbee/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Влад Пимонов
title: Backend developer
email: pimonowlad@gmail.com
website: ineverbee.github.io/resume

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: ineverbee
github_username:  ineverbee
instagram_username: ineverbee
# youtube_username: globalmtb

# Additional icon links
additional_links:
- title: Telegram Link
  icon: fas fa-paper-plane
  url: https://www.t.me/ineverbee
- title: HackerRank Link
  icon: fab fa-hackerrank
  url: https://www.hackerrank.com/pimonowlad

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/zenitsu.jpg
about_content: | # this will include new lines to allow paragraphs
  Привет, меня зовут Влад, я начинающий backend разработчик. Я разрабатывал свои проекты на <mark>Golang</mark> и <mark>Python</mark>, и удачно заливал их на <mark>Heroku</mark>. Я проходил стажировку в компании <mark>Wildberries</mark> на позиции <mark>Golang</mark> разработчика. Также я практиковал свои теоретические знания языков программирования, в том числе <mark>SQL</mark>, на <mark>HackerRank</mark>; ссылка на профиль есть выше.

  Мои наиболее прокаченные скиллы: <mark>Golang</mark> и <mark>Watching anime</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Wall
        # quote: >
        #  Add anything you want
        link: github.com/ineverbee/go-web
        # link_text: Project Website
        additional_links:
          - title:  ineverbee/go-web
            icon: fab fa-github
            url: github.com/ineverbee/go-web
        description: | # this will include new lines to allow paragraphs
          Я начал этот проект для изучения языка <mark>Go</mark>, его стандартных библиотек и для практики разработки на данном языке. Во время написания этого проекта я также изучил <mark>NoSQL</mark> на примере <mark>MongoDB</mark> и <mark>OAuth v2.0</mark> при этом используя <mark>VK API</mark>.
      - layout: top-middle
        title: Backend-test-go
        # quote: >
        #  Add anything you want
        link: github.com/ineverbee/backend-test-go
        # link_text: Project Website
        additional_links:
          - title:  ineverbee/backend-test-go
            icon: fab fa-github
            url: github.com/ineverbee/backend-test-go
        description: | # this will include new lines to allow paragraphs
          Проект как тестовое задание для вакансии стажёра backend разработки в Авито, а также как практика разработки на <mark>Go</mark>. Во время написания этого проекта я также изучил <mark>Redis</mark>.
      - layout: top-middle
        title: fibonacci
        # quote: >
        #  Add anything you want
        link: github.com/ineverbee/fibonacci
        # link_text: Project Website
        additional_links:
          - title:  ineverbee/fibonacci
            icon: fab fa-github
            url: github.com/ineverbee/fibonacci
        description: | # this will include new lines to allow paragraphs
          Проект как тестовое задание для вакансии junior backend разработчика Golang в FBS. Микросервис для создания среза чисел Фибоначчи с двумя протоколами <mark>HTTP REST</mark> и <mark>gRPC</mark>.
      - layout: top-middle
        title: bitlybutnot
        # quote: >
        #  Add anything you want
        link: github.com/ineverbee/bitlybutnot
        # link_text: Project Website
        additional_links:
          - title:  ineverbee/bitlybutnot
            icon: fab fa-github
            url: github.com/ineverbee/bitlybutnot
        description: | # this will include new lines to allow paragraphs
          Тестовое задание для вакансии стажёра backend разработчика Golang в Ozon. <mark>HTTP REST</mark> сервис для укорачивания длинных ссылок.
      - layout: top-middle
        title: adverts-go-api
        # quote: >
        #  Add anything you want
        link: github.com/ineverbee/adverts-go-api
        # link_text: Project Website
        additional_links:
          - title:  ineverbee/adverts-go-api
            icon: fab fa-github
            url: github.com/ineverbee/adverts-go-api
        description: | # this will include new lines to allow paragraphs
          Сервис для хранения и подачи объявлений, хранящихся в базе данных <mark>Postgres</mark>. Сервис предоставляет API, работающее поверх <mark>HTTP</mark> в формате <mark>JSON</mark>.
      - layout: top-middle
        title: catalogue
        # quote: >
        #  Add anything you want
        link: github.com/ineverbee/catalogue
        # link_text: Project Website
        additional_links:
          - title:  ineverbee/catalogue
            icon: fab fa-github
            url: github.com/ineverbee/catalogue
        description: | # this will include new lines to allow paragraphs
          Сервис для работы с базой данных котов <mark>Postgres</mark> через <mark>Go</mark>. Сервис предоставляет API для получения списка котов, для добавления новых котов и что-то ещё.


  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content:
      <p><font size="5"><mark>Golang</mark></font>&#9;<font size="5"><mark>Python</mark></font>&#9;<font size="5"><mark>Gorilla Toolkit</mark></font>&#9;<font size="5"><mark>Django</mark></font>&#9;<font size="5"><mark>Git</mark></font>&#9;<font size="5"><mark>HTML</mark></font>&#9;<font size="5"><mark>CSS</mark></font>&#9;<font size="5"><mark>JS</mark></font>&#9;<font size="5"><mark>jQuery</mark></font>&#9;<font size="5"><mark>Docker</mark></font>&#9;<font size="5"><mark>Heroku</mark></font>&#9;<font size="5"><mark>Redis</mark></font>&#9;<font size="5"><mark>Linux</mark></font>&#9;<font size="5"><mark>SQL</mark></font>&#9;<font size="5"><mark>PostgreSQL</mark></font>&#9;<font size="5"><mark>NoSQL</mark></font>&#9;<font size="5"><mark>MongoDB</mark></font>&#9;<font size="5"><mark>gRPC</mark></font></p>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: НИТУ МИСиС
        caption: 2016 - 2020
        sub_title: Электроника и наноэлектроника
        quote: >
          Национальный исследовательский технологический университет «МИСиС» — российский технический университет; первый вуз в стране, получивший статус «Национального исследовательского технологического университета».
        description: | # this will include new lines to allow paragraphs
          Во время учебы в университете я усвоил большинство ключевых навыков, таких как командная работа и работа в сжатые сроки. Я получил огромное удовольствие от учебы в университете и много узнал о здоровом балансе между работой и личной жизнью.
      - layout: left
        title: НИТУ МИСиС
        caption: 2020
        sub_title: IELTS
        description: | # this will include new lines to allow paragraphs
          Upper intermediate - B2

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Стажер GO разработчик
        caption: July 2022 - September 2022
        sub_title: Wildberries
        quote: >
          Международный маркетплейс одежды, обуви, электроники, детских товаров, товаров для дома и других товаров.
        description: | # this will include new lines to allow paragraphs
          В качестве теоретической части разрабатывал <mark>Linux</mark> утилиты, а также задачи на го на алгоритмы и шаблоны проектирования. На практической части создавал приложения для работы с <mark>Postgres</mark> базой данных и <mark>Nats Streaming</mark>.
      

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Наряду с моим интересом к backend разработке, некоторые из моих других интересов и хобби:
      - Anime
      - Gaming
      - Video and image editing
      - Drawing
      - [Photography](https://instagram.com/ineverbee)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
