# Site
repository: ineverbee/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Влад Пимонов
title: Backend developer
email: pimonowlad@gmail.com
website: ineverbee.herokuapp.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  ineverbee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ineverbee
# telegram_username: ineverbee
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Telegram Link
  icon: fas fa-paper-plane
  url: https://www.t.me/ineverbee
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/itadori.jpg
about_content: | # this will include new lines to allow paragraphs
  Привет, моё имя Влад, мне 22 и я backend разработчик. У меня нет опыта работы в реальном производстве. Но я писал свои проекты на <mark>Golang</mark> и <mark>Python</mark>, и удачно заливал их на <mark>Heroku</mark>.

  Мои наиболее прокаченные скиллы: <mark>Django</mark> и <mark>Watching anime</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Wall
        link: github.com/ineverbee
        link_text: Project Website
        additional_links:
          - title:  ineverbee/go-web
            icon: fab fa-github
            url: github.com/ineverbee/go-web
        quote: >
          Add anything you want
        description: | # this will include new lines to allow paragraphs
          Я начал этот проект для изучения языка <mark>Go</mark>, его стандартных библиотек и для практики разработки на данном языке. Во время написания этого проекта я также изучил <mark>NoSQL</mark> на примере <mark>MongoDB</mark> и <mark>OAuth v2.0</mark> при этом используя <mark>VK API</mark>.

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content:
      <h2>Python</h2> <h2>Golang</h2>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: НИТУ МИСиС
        caption: 2016 - 2020
        sub_title: Электроника и наноэлектроника
        quote: >
          Национальный исследовательский технологический университет «МИСиС» — российский технический университет; первый вуз в стране, получивший статус «Национального исследовательского технологического университета».
        description: | # this will include new lines to allow paragraphs
          Во время учебы в университете я усвоил большинство ключевых навыков, таких как командная работа и работа в сжатые сроки. Я получил огромное удовольствие от учебы в университете и много узнал о здоровом балансе между работой и личной жизнью.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Наряду с моим интересом к backend разработке, некоторые из моих других интересов и хобби:
      - Anime
      - Gaming
      - Video editing
      - [Photography](https://instagram.com/ineverbee)

      Look at this cool image  
      ![Image](images/image.png "Image")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
