# Site
repository: ineverbee/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Влад Пимонов
title: Software developer
email: pimonowlad@gmail.com
website: ineverbee.github.io/resume

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: ineverbee
github_username:  ineverbee
instagram_username: ineverbee
# youtube_username: globalmtb

# Additional icon links
additional_links:
- title: Telegram Link
  icon: fas fa-paper-plane
  url: https://www.t.me/ineverbee
- title: LeetCode Link
  icon: fas fa-code
  url: https://leetcode.com/ineverbee/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/loading_cat.jpg
about_content: | # this will include new lines to allow paragraphs
  Привет, меня зовут Влад, и я опытный разработчик программного обеспечения на языке <mark>Golang</mark> с глубокими знаниями в области сетевых технологий. В своей работе я специализируюсь на разработке решений, связанных с прокси-серверами, <mark>VPN</mark>, <mark>DNS</mark>, а также протоколами <mark>TCP/IP</mark>, <mark>UDP</mark>, <mark>HTTP</mark> и <mark>HTTPS</mark>.

  Помимо Golang, я также владею языком <mark>Python</mark>, что позволяет мне расширять функциональность разрабатываемых приложений и эффективно решать разнообразные задачи. Я активно использую инструменты, такие как <mark>Git</mark> и <mark>Docker</mark>, для управления версиями и контейнеризации, а также работал с <mark>Redis</mark> и <mark>MongoDB</mark> для хранения и обработки данных.

  Мои наиболее прокаченные скиллы: <mark>Golang</mark> и <mark>Linux terminal</mark>

content:
  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content:
      <p><font size="8"><mark>Golang</mark></font>&#9;<font size="6"><mark>Python</mark></font>&#9;<font size="5"><mark>Bash</mark></font>&#9;<font size="3"><mark>Git</mark></font>&#9;<font size="4"><mark>MongoDB</mark></font>&#9;<font size="6"><mark>Docker</mark></font>&#9;<font size="5"><mark>Redis</mark></font>&#9;<font size="7"><mark>Linux</mark></font>&#9;<font size="4"><mark>SQL</mark></font>&#9;<font size="6"><mark>API</mark></font>&#9;<font size="5"><mark>HTTP</mark></font>&#9;<font size="5"><mark>TCP/IP</mark></font>&#9;<font size="3"><mark>TLS</mark></font></p>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: НИТУ МИСиС
        caption: 2016 - 2020
        sub_title: Электроника и наноэлектроника
        quote: >
          Национальный исследовательский технологический университет «МИСиС» — российский технический университет; первый вуз в стране, получивший статус «Национального исследовательского технологического университета».
        description: | # this will include new lines to allow paragraphs
          Во время учебы в университете я усвоил большинство ключевых навыков, таких как командная работа и работа в сжатые сроки. Я получил огромное удовольствие от учебы в университете и много узнал о здоровом балансе между работой и личной жизнью.
      - layout: left
        title: НИТУ МИСиС
        caption: 2020
        sub_title: IELTS
        description: | # this will include new lines to allow paragraphs
          Upper intermediate - B2     

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Наряду с моим интересом к разработке, некоторые из моих других интересов и хобби:
      - Anime
      - Gaming
      - Video and image editing
      - Drawing
      - [Photography](https://instagram.com/ineverbee)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
